### ISSUE TITLE
Minecraft crashed when execute command "/playPlayerAnimation @p playeranimatorapi:gecko"

### ISSUE THREAD

**Issue by wellwhz** [ZigyTheBird/ZigysPlayerAnimatorAPI#4]
I've add the AzureLib. But when I execute command, Minecraft crashed.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-04-28 13:18:29
Description: Ticking entity

java.lang.NoClassDefFoundError: zigy.playeranimatorapi.mixin.PlayerMixin_azureOnly is invalid
	at net.minecraft.world.entity.player.Player.registerControllers(Player.java:2731) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin_azureOnly,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at mod.azure.azurelib.core.animation.AnimatableManager.<init>(AnimatableManager.java:40) ~[azurelib-neo-1.20.1-2.0.21.jar%23160!/:2.0.21] {re:mixin,re:classloading,pl:mixin:APP:playeranimatorapi-common.mixins.json:AnimatableManagerAccessor_azureOnly,pl:mixin:A}
	at mod.azure.azurelib.core.animatable.instance.InstancedAnimatableInstanceCache.getManagerForId(InstancedAnimatableInstanceCache.java:24) ~[azurelib-neo-1.20.1-2.0.21.jar%23160!/:2.0.21] {re:classloading}
	at zigy.playeranimatorapi.azure.ModAzureUtilsClient.tick(ModAzureUtilsClient.java:33) ~[playeranimatorapi-forge-1.20.1-1.3.3.jar%23162!/:?] {re:mixin,re:classloading}
	at zigy.playeranimatorapi.events.ClientPlayerTickEvent.tick(ClientPlayerTickEvent.java:29) ~[playeranimatorapi-forge-1.20.1-1.3.3.jar%23162!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.player.Player.handler$zzi000$inject(Player.java:2226) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin_azureOnly,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin_azureOnly,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.player.AbstractClientPlayer.m_8119_(AbstractClientPlayer.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1814) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.entity.player.Player.registerControllers(Player.java:2731) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin_azureOnly,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at mod.azure.azurelib.core.animation.AnimatableManager.<init>(AnimatableManager.java:40) ~[azurelib-neo-1.20.1-2.0.21.jar%23160!/:2.0.21] {re:mixin,re:classloading,pl:mixin:APP:playeranimatorapi-common.mixins.json:AnimatableManagerAccessor_azureOnly,pl:mixin:A}
	at mod.azure.azurelib.core.animatable.instance.InstancedAnimatableInstanceCache.getManagerForId(InstancedAnimatableInstanceCache.java:24) ~[azurelib-neo-1.20.1-2.0.21.jar%23160!/:2.0.21] {re:classloading}
	at zigy.playeranimatorapi.azure.ModAzureUtilsClient.tick(ModAzureUtilsClient.java:33) ~[playeranimatorapi-forge-1.20.1-1.3.3.jar%23162!/:?] {re:mixin,re:classloading}
	at zigy.playeranimatorapi.events.ClientPlayerTickEvent.tick(ClientPlayerTickEvent.java:29) ~[playeranimatorapi-forge-1.20.1-1.3.3.jar%23162!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.player.Player.handler$zzi000$inject(Player.java:2226) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin_azureOnly,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin,pl:mixin:APP:playeranimatorapi-common.mixins.json:PlayerMixin_azureOnly,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.player.AbstractClientPlayer.m_8119_(AbstractClientPlayer.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.client.player.LocalPlayer)
	Entity ID: 1
	Entity Name: wellwhz
	Entity's Exact location: 7.06, -60.00, -6.45
	Entity's Block location: World: (7,-60,-7), Section: (at 7,4,9 in 0,-4,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1814) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by ZigyTheBird** [comment]
Hello there!
Sorry for taking so long Gmail thought that the GitHub notification email was just spam so I only found out about your issue today....
Hopefully that won't happen again
Anyways I couldn't replicate the issue on my own
Is this issue occuring in a dev environment?
You should try using an older version of the Forge loader like 47.1.0 or the latest version of NeoForge
AzureLib is developed for NeoForge so that might be the cause of the issue?
If this isn't in a dev environment then I would like to know the list of mods you are using or if you are using a dev environment I would like to take a look if possible
Thanks for taking the time to report this 🙏

**Comment by wellwhz** [comment]
This issue doesn't occur in dev environment.
I use NeoForge 47.1.105.
Here are the mod lists.

azurelib-neo-1.20.1-2.0.21
player-animation-lib-forge-1.0.2-rc1+1.20
playeranimatorapi-forge-1.20.1-1.3.3

**Comment by ZigyTheBird** [comment]
Should be fixed in version 1.3.4
Give it a try and get back to me

**Comment by wellwhz** [comment]
I've tried it. It was fixed
