### ISSUE TITLE
Minecraft Report An Error While Loading

### ISSUE THREAD

**Issue by wellwhz** [ZigyTheBird/ZigysPlayerAnimatorAPI#5]
ava.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.105-universal.jar%23171!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.1.105-universal.jar%23171!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:148) ~[forge-1.20.1-47.1.105-universal.jar%23171!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:958) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelib.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.105.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap.put(Object2ObjectArrayMap.java:375) ~[fastutil-8.5.9.jar%23129!/:?] {}
-- MOD playeranimatorapi --
Details:
	Mod File: /C:/Users/25147/AppData/Roaming/Minecraft 1.20.1 NeoForge 47.1.105/mods/[P][前置][玩家动画]playeranimatorapi-forge-1.20.1-1.3.4.jar
	Failure message: Zigy's Player Animator API (playeranimatorapi) has failed to load correctly
		java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
	Mod Version: 1.3.4
	Mod Issue URL: https://github.com/ZigyTheBird/ZigysPlayerAnimatorAPI/issues
	Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap.put(Object2ObjectArrayMap.java:375) ~[fastutil-8.5.9.jar%23129!/:?] {}
	at net.minecraftforge.network.simple.IndexedMessageCodec$MessageHandler.<init>(IndexedMessageCodec.java:75) ~[forge-1.20.1-47.1.105-universal.jar%23171!/:?] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.addCodecIndex(IndexedMessageCodec.java:157) ~[forge-1.20.1-47.1.105-universal.jar%23171!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.registerMessage(SimpleChannel.java:76) ~[forge-1.20.1-47.1.105-universal.jar%23171!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.registerMessage(SimpleChannel.java:72) ~[forge-1.20.1-47.1.105-universal.jar%23171!/:?] {re:classloading}
	at mod.azure.azurelib.platform.NeoForgeAzureLibNetwork.registerClientReceiverPackets(NeoForgeAzureLibNetwork.java:47) ~[%5BA%5D%5B前置%5D%5B动画引擎%5Dazurelib-neo-1.20.1-2.0.22.jar%23161!/:2.0.22] {re:classloading}
	at mod.azure.azurelib.platform.NeoForgeAzureLibInitializer.initialize(NeoForgeAzureLibInitializer.java:15) ~[%5BA%5D%5B前置%5D%5B动画引擎%5Dazurelib-neo-1.20.1-2.0.22.jar%23161!/:2.0.22] {re:classloading}
	at mod.azure.azurelib.AzureLib.initialize(AzureLib.java:25) ~[%5BA%5D%5B前置%5D%5B动画引擎%5Dazurelib-neo-1.20.1-2.0.22.jar%23161!/:2.0.22] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:classloading}
	at zigy.playeranimatorapi.azure.ModAzureUtils.init(ModAzureUtils.java:8) ~[%5BP%5D%5B前置%5D%5B玩家动画%5Dplayeranimatorapi-forge-1.20.1-1.3.4.jar%23165!/:?] {re:classloading}
	at zigy.playeranimatorapi.ModInit.init(ModInit.java:18) ~[%5BP%5D%5B前置%5D%5B玩家动画%5Dplayeranimatorapi-forge-1.20.1-1.3.4.jar%23165!/:?] {re:classloading}
	at zigy.playeranimatorapi.forge.PlayerAnimatorAPIModForge.<init>(PlayerAnimatorAPIModForge.java:16) ~[%5BP%5D%5B前置%5D%5B玩家动画%5Dplayeranimatorapi-forge-1.20.1-1.3.4.jar%23165!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:75) ~[language-java-47.2.2.jar%23168!/:47.2] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[core-47.2.2.jar%23167!/:47.2] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

NeoForge 47.1.105

**Comment by wellwhz** [comment]
It will happen sometimes. It's not every time when I launch.

**Comment by ZigyTheBird** [comment]
I have known about this issue for a while
It might be an AzureLib bug? IDK
I am gonna look into it and I will keep you updated here

**Comment by ZigyTheBird** [comment]
I told AzureDoom about this issue but sadly they didn't know much about this
Sadly I can't do much here either since I have had this problem in other projects so it's prob not my fault
I am just gonna hope that with time this issue will go away
